[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ParoQuant"
version = "0.1.0"
description = "An efficient and accurate weight quantization(INT3/4) method for LLMs."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
]
dependencies = [
]

[tool.setuptools.packages.find]
exclude = ["experiments*", "kernels*", "scripts*"]

[tool.wheel]
exclude = ["experiments*", "kernels*", "scripts*"]
